# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokrivator_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pokrivator_editor(object):
    def setupUi(self, pokrivator_editor):
        pokrivator_editor.setObjectName("pokrivator_editor")
        pokrivator_editor.resize(541, 293)
        self.buttonBox = QtWidgets.QDialogButtonBox(pokrivator_editor)
        self.buttonBox.setGeometry(QtCore.QRect(170, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.radioButton = QtWidgets.QRadioButton(pokrivator_editor)
        self.radioButton.setGeometry(QtCore.QRect(350, 120, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(pokrivator_editor)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(pokrivator_editor)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 150, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.editor_short_name = QtWidgets.QComboBox(pokrivator_editor)
        self.editor_short_name.setGeometry(QtCore.QRect(20, 40, 181, 31))
        self.editor_short_name.setEditable(True)
        self.editor_short_name.setObjectName("editor_short_name")
        self.label = QtWidgets.QLabel(pokrivator_editor)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label.setObjectName("label")
        self.editor_sell_quantity = QtWidgets.QLineEdit(pokrivator_editor)
        self.editor_sell_quantity.setGeometry(QtCore.QRect(70, 100, 113, 20))
        self.editor_sell_quantity.setObjectName("editor_sell_quantity")
        self.label_2 = QtWidgets.QLabel(pokrivator_editor)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(pokrivator_editor)
        self.label_3.setGeometry(QtCore.QRect(190, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(pokrivator_editor)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 61, 16))
        self.label_4.setObjectName("label_4")
        self.editor_price = QtWidgets.QLineEdit(pokrivator_editor)
        self.editor_price.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.editor_price.setObjectName("editor_price")
        self.label_5 = QtWidgets.QLabel(pokrivator_editor)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 111, 16))
        self.label_5.setObjectName("label_5")
        self.editor_min_bid = QtWidgets.QLineEdit(pokrivator_editor)
        self.editor_min_bid.setGeometry(QtCore.QRect(120, 180, 113, 20))
        self.editor_min_bid.setObjectName("editor_min_bid")
        self.label_6 = QtWidgets.QLabel(pokrivator_editor)
        self.label_6.setGeometry(QtCore.QRect(230, 20, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(pokrivator_editor)
        self.label_7.setGeometry(QtCore.QRect(390, 20, 141, 16))
        self.label_7.setObjectName("label_7")
        self.editor_sec_code = QtWidgets.QLineEdit(pokrivator_editor)
        self.editor_sec_code.setGeometry(QtCore.QRect(230, 40, 131, 31))
        self.editor_sec_code.setObjectName("editor_sec_code")
        self.editor_class_code = QtWidgets.QLineEdit(pokrivator_editor)
        self.editor_class_code.setGeometry(QtCore.QRect(390, 40, 131, 31))
        self.editor_class_code.setObjectName("editor_class_code")
        self.radioButton_3 = QtWidgets.QRadioButton(pokrivator_editor)
        self.radioButton_3.setGeometry(QtCore.QRect(350, 180, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)

        self.retranslateUi(pokrivator_editor)
        self.buttonBox.accepted.connect(pokrivator_editor.accept) # type: ignore
        self.buttonBox.rejected.connect(pokrivator_editor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(pokrivator_editor)

    def retranslateUi(self, pokrivator_editor):
        _translate = QtCore.QCoreApplication.translate
        pokrivator_editor.setWindowTitle(_translate("pokrivator_editor", "Dialog"))
        self.radioButton.setText(_translate("pokrivator_editor", "Main"))
        self.radioButton_2.setText(_translate("pokrivator_editor", "6 mln"))
        self.label.setText(_translate("pokrivator_editor", "Инструмент"))
        self.label_2.setText(_translate("pokrivator_editor", "Продать"))
        self.label_3.setText(_translate("pokrivator_editor", "лотов"))
        self.label_4.setText(_translate("pokrivator_editor", "не дешевле"))
        self.label_5.setText(_translate("pokrivator_editor", "если бид больше"))
        self.label_6.setText(_translate("pokrivator_editor", "Код инструмента"))
        self.label_7.setText(_translate("pokrivator_editor", "Класс"))
        self.radioButton_3.setText(_translate("pokrivator_editor", "ИИС"))
